### ISSUE TITLE
Supported only with traefik enterprise?

### ISSUE THREAD

**Issue by swagftw** [team-carepay/traefik-jwt-plugin#22]
Seems like `custom plugins` are only supported as part of the `Traefik enterprise` solution. Is that the case? As stated [here](https://traefik.io/pricing/) in pricing section.

If custom plugins are only supported with `Traefik enterprise`, is there any way we can use these custom plugins with `Traefik proxy open source` solution or any other work around?

**Comment by blagerweij** [comment]
Hmm, that would be new for me. We're using plugins with the open-source version without any issue. In fact, if you read this blog post https://traefik.io/blog/expand-the-power-of-traefik-proxy-with-custom-plugins/ , you'll notice they have removed the need for a pilot token (which was required before). Plugins are also documented on the open-source section.

One thing to notice, though: Traefik Enterprise comes with a few proprietary plugins developed by Traefik themselves. They provide one for JWT, and one for OPA. See https://doc.traefik.io/traefik-enterprise/middlewares/jwt/

**Comment by swagftw** [comment]
Let me try removing pilot token

**Comment by swagftw** [comment]
It is working after upgrading the traefik to latest version. Closing the issue.
