### ISSUE TITLE
[proposal] Make JWT token optional

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [team-carepay/traefik-jwt-plugin#23]
Hello 

We would like to use this plugin for OPA based AuthZ implementation, but currently we can not use it for one of the cases.

We'd like to delegate to OPA for decesions for endpoints that are "public", i.e. there no need to pass JWT token for those pages.

But, currently plugin consider `Authorization` header as mandatory and immediately fails.
So, I propose to introduce a new parameter that will make `Authorization` header optional, so even if header is missing - the decision will still be asked from OPA.

I realize that setting `Required` to false is solving my problem, but in this case I will miss required payload claims validation.

What do you think ? In case you're interesting - I'm ready to provide a PR.

**Comment by blagerweij** [comment]
Sounds good, especially if we make the flag default to false, which means we're backwards compatible.
Which name did you have in mind for the new flag ? Feel free to submit a PR

**Comment by ievgenii-shepeliuk** [comment]
What about `JwtRequired` or `JwtHeaderRequired` ?

**Comment by ievgenii-shepeliuk** [comment]
Also included a fix for empty JSON body into that PR.

**Comment by ievgenii-shepeliuk** [comment]
Hello @blagerweij 
Thnx for merging the PR
Could you please create a release tag for this commit ?

**Comment by blagerweij** [comment]
Hi @ievgenii-shepeliuk ,

It's done, see v0.1.0 tag.

**Comment by ievgenii-shepeliuk** [comment]
Thanks a lot
