### ISSUE TITLE
Does it check expiration date?

### ISSUE THREAD

**Issue by myagmarsurensedjav** [team-carepay/traefik-jwt-plugin#24]
If it does, how can I configure? Or if it doesn't, how can I implement it? Please advise.

**Comment by ievgenii-shepeliuk** [comment]
This plugin can only check for a presence of a claim in token at the moment.
You can implement token expiration verification and other checks in OPA policies instead.

**Comment by blagerweij** [comment]
Using OPA is optional, I guess we can add support for 'iat' and 'exp' in the plugin as well

**Comment by blagerweij** [comment]
@myagmarsurensedjav please check v0.1.1, I have added support for 'exp' and 'iat' checks.
You'll need to add them to 'PayloadFields', to enforce that the fields are present and valid.

**Comment by myagmarsurensedjav** [comment]
@blagerweij it works great! thank you.
