### ISSUE TITLE
[proposal] Allow to skip request body parsing via config flag

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [team-carepay/traefik-jwt-plugin#27]
Hello

Currently plugin tries to parse request body to pass corresponding info to OPA.
The 1st issue is that this is not mentioned anywhere in docs, so I suggest a corresponding section should be added to README.

2nd issue is that body parsing is quite resource consuming operation and may introduce latencies that are not desirable in high volume application. So I have another proposal to introduce a flag that can completely disable parsing of request body. If you're interested I am willing to provide a PR.

**Comment by ievgenii-shepeliuk** [comment]
Hello @blagerweij 
I think your latest commit already implements this fature. So the issue may be closed. Am I right ?

**Comment by blagerweij** [comment]
Yeah, I just need to make a new release, then we can close this issue
