### ISSUE TITLE
[proposal] Deprecate traefik-opa-plugin

### ISSUE THREAD

**Issue by eshepelyuk** [team-carepay/traefik-jwt-plugin#42]
Hello @blagerweij 

I am proposing to deprecate, i.e. archive https://github.com/team-carepay/traefik-opa-plugin.

That plugin was not updated for long time and is completely superseed by `traefik-jwt-plugin`.

The current plugin is much more flexible regarding OPA interaction, allowing to use headers, policy driven status code etc.

Even if users do not want to use JWT verification, they still can use current plugin, e.g. my company uses this plugin without JWT token verification, because we do it on OPA side.

**Comment by blagerweij** [comment]
Yeah, that's a good point. I've never archived a project, let me see how we can achieve this. I believe that removing the label / tag will also ensure it's removed from the Traefik pilot website....

**Comment by eshepelyuk** [comment]
> Yeah, that's a good point. I've never archived a project, let me see how we can achieve this. I believe that removing the label / tag will also ensure it's removed from the Traefik pilot website....

Go to "Settings" tab and scroll to the bottom to "Danger zone"

**Comment by eshepelyuk** [comment]
Also it would be great if you add some words about OPA into this plugin "About" as well as add label/topic opa to it.

**Comment by blagerweij** [comment]
Done. Other plugin is archived, readme and about updated
