### ISSUE TITLE
How to verify Alg, Iss and Aud?

### ISSUE THREAD

**Issue by latenssi** [team-carepay/traefik-jwt-plugin#44]
In the readme (https://github.com/team-carepay/traefik-jwt-plugin/blob/main/README.md?plain=1#L54-L55) it states that one can provide values via config for `Iss` and `Aud` and that these would be "Used to verify" them in the token. Adding those in the config does not seem to have any effect and looking at the source code it seems they are not used in anywhere.

Am I missing something or is the documentation wrong?

edit: removed `Alg` as that seems to be actually verified

**Comment by ievgenii-shepeliuk** [comment]
E.g. code for `Alg`
https://github.com/team-carepay/traefik-jwt-plugin/blob/main/jwt.go#L539-L541

**Comment by latenssi** [comment]
Thank you @ievgenii-shepeliuk! Do you know how `Aud` and `Iss` are handled?

**Comment by eshepelyuk** [comment]
Hello
The documentation is wrong, those fields are not used y the plugin.

**Comment by latenssi** [comment]
Thank you @eshepelyuk for clearing this up!
