### ISSUE TITLE
Problem with preflight request

### ISSUE THREAD

**Issue by belgi4n** [team-carepay/traefik-jwt-plugin#46]
Hello,

I’m using the plugin to validate a jwt token with traefik, I’m not using OPA. However when I’m doing a request from the front-end, the preflight request generated by the browser is failing with an error 403 "authorization header missing" because there are no Authorization header in a preflight request. What can I do to solve that problem ?

**Comment by eshepelyuk** [comment]
Hello @belgi4n 

You can

*. Set `Required` flag in settings to false, thus making JWT token optional.
* Or adjust routing, so the plugin will be only applied to POST/GET and not applied to OPTIONS method.

**Comment by michalsteyn** [comment]
I have just spent an entire day to try and get this working.

Setting Required to false really doesn't sound like a solution, doesn't that negate the entire purpose of this plugin? 

What is the easiest way to do this: `Or adjust routing, so the plugin will be applied only to POST/GET and not applied to OPTIONS method.` Does that require creating multiple ingresses per service? 

If anyone could provide an example, that would be amazing.

P.S.
The Kong JTW Plugin has a flag: `run_on_preflight: false` this makes it extremely easy to handle this situation. Would be awesome to have that added here as well.

**Comment by foto-andreas** [comment]
Hi,

I encountered the same problem today. Any known solutions for the "adjust routing" solution?

Andreas
