### ISSUE TITLE
opa response set in the http response to the client when the request isn't allowed

### ISSUE THREAD

**Issue by yoeluk** [team-carepay/traefik-jwt-plugin#47]
The response from Opa is set in the response to the client with the response isn't allowed. While this is useful when developing and debugging in a production system this can lead to a leak of policy and data details to a bad actor.

An example of such responses is `{"result":{"allow":false,"cert":[],"customer_id":"<redacted>"}}`

**Comment by yoeluk** [comment]
Hey @eshepelyuk let's do that, I don't want to wait too long to have this reviewed since as it stands isn't safe to use in production (unless you get your contributor powers back)

**Comment by blagerweij** [comment]
Thanks for the PR, when the review comments are addressed we can merge and release a new version.... For me the main showstopper is the README formatting, once that's fixed we can release.

**Comment by yoeluk** [comment]
@blagerweij @eshepelyuk Hopefully we can merge this soon so that I can remove my forks from the traefik public archive in favour of this. As I mentioned, we considered this critical for our production system to protect opa policy details.
